#pragma once

#include <Arduino.h>

#define AMG_COLS 8
#define AMG_ROWS 8

#define INTERPOLATED_COLS 24
#define INTERPOLATED_ROWS 24

#define SPACE_BETWEEN_COLUMNS 3

#define SHORTEST_AUTO_TEMPERATURE_INTERVAL 5

#define DEFAULT_MIN_TEMPERATURE 20
#define DEFAULT_MAX_TEMPERATURE 32
